[package]
name = "typed-open-graph"
description = "The Open Graph Protocol Builder"
version = "0.1.1"
edition = "2024"
readme = "README.md"
repository = "https://github.com/cjtoolkit/typed-open-graph"
license = "MIT"
keywords = ["opengraph", "facebook", "social", "meta", "linkedin"]

[package.metadata.docs.rs]
all-features = true

[features]
chrono = ["dep:chrono"]

[dependencies]
url = "2.5.7"

chrono = { version = "0.4.42", optional = true }